
title: IoThingy
lang: en
description: >-
  Core library for writing your own IoThingies by implementing your custom
  peripherals and/or using existing ones from other projects. It uses MQTT to
  send metrics of each peripheral and/or receive commands to change state.

remote_theme: rundocs/jekyll-rtd-theme
repository: iothingy/website
url: "https://iothingy.io/"
#baseurl: "/"

## local method ##
# theme: jekyll-rtd-theme
# debug:
#   compress: false
#   dist: true
#   shortcodes: true

## remote method ##

readme_index:
  with_frontmatter: true

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions


# FROM: https://rundocs.io/configuring/defaults.html#configuration-from-github-pages
lsi: false
safe: true
source: iothingy/website
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

